env:
  browser: true
  es2021: true
extends: ['airbnb-base/legacy', 'prettier', 'plugin:node/recommended']
plugins: ['prettier']
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules: {
  prettier/prettier: error,
  no-var: warn,
  no-unused-vars: warn,
  no-console: warn,
  func-names: off,
  spaced-comment: off,
}